{% set version = "2.3.10" %}

{% set build_noarch = False %}
{% set build_noarch = True %}  # [ppc64le and py==312]
{% set build_number = 3 %}

package:
  name: frozendict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/frozendict/frozendict-{{ version }}.tar.gz
  sha256: aadc83510ce82751a0bb3575231f778bc37cbb373f5f05a52b888e26cbb92f79

build:
  number: {{ build_number * 2 + 1 }}

outputs:
  {% if build_noarch %}
  - name: frozendict
    build:
      noarch: python
      number: {{ build_number * 2 }}
      script:
        - FROZENDICT_PURE_PY=1 python setup.py bdist_wheel
        - python -m pip install --no-deps -vv dist/*.whl
    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools
        - wheel
      run:
        - python >=3.7
    test:
      imports:
        - frozendict
      requires:
        - pip
      commands:
        - pip check
  {% endif %}

  - name: frozendict
    build:
      number: {{ build_number * 2 + 1 }}
      script: python -m pip install . --no-deps -vv --no-build-isolation
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - frozendict
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
