{% set name = "frozendict" %}
{% set version = "2.4.5" %}
{% set sha256 = "fd7add309789595c044c0155a0bddfa9d20c77f65de1e33a14aa3033b936ef63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - frozendict

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
