{% set name = "frozendict" %}
{% set version = "2.3.3" %}
{% set sha256 = "398539c52af3c647d103185bbaa1291679f0507ad035fe3bab2a8b0366d52cf1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps -vv

    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
