{% set name = "frozendict" %}
{% set version = "2.3.10" %}
{% set sha256 = "aadc83510ce82751a0bb3575231f778bc37cbb373f5f05a52b888e26cbb92f79" %}
{% set build_number = 3 %}

package:
  name: frozendict-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps -vv         # [build_noarch == 'no']
      number: {{ build_number * 2 }}                        # [build_noarch == 'no']
      script: FROZENDICT_PURE_PY=1 python setup.py install  # [build_noarch == 'yes']
      noarch: python                                        # [build_noarch == 'yes']
      number: {{ build_number * 2 + 1 }}                    # [build_noarch == 'yes']

    requirements:
      build:                                     # [build_noarch == 'no']
        - python                                 # [build_noarch== 'no' and build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_noarch== 'no' and build_platform != target_platform]
        - {{ compiler('c') }}                    # [build_noarch == 'no']
      host:
        - pip
        - python        # [build_noarch == 'no']
        - python >=3.7  # [build_noarch == 'yes']
        - setuptools
        - wheel
      run:
        - python        # [build_noarch == 'no']
        - python >=3.7  # [build_noarch == 'yes']

    test:
      imports:
        - frozendict

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
