{% set name = "frozendict" %}
{% set version = "2.3.10" %}
{% set sha256 = "aadc83510ce82751a0bb3575231f778bc37cbb373f5f05a52b888e26cbb92f79" %}

{% set build_noarch = False %}
{% set build_noarch = True %}  # [ppc64le and py==312]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps -vv

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict

  {% if build_noarch %}
  - name: {{ name }}
    build:
      script: FROZENDICT_PURE_PY=1 python setup.py install
      noarch: python
      number: 2

    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict
  {% endif %}

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
