{% set name = "frozendict" %}
{% set version = "2.3.0" %}
{% set sha256 = "da4231adefc5928e7810da2732269d3ad7b5616295b3e693746392a8205ea0b5" %}

{% set build_noarch = True if (linux64 and py==310) else False %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3

outputs:
  {% if build_noarch %}
  - name: {{ name }}
    build:
      script: python setup.py py install
      noarch: python
      number: 4

    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict
  {% else %}
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps -vv

    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict
  {% endif %}

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
