{% set name = "frozendict" %}
{% set version = "2.3.10" %}
{% set sha256 = "aadc83510ce82751a0bb3575231f778bc37cbb373f5f05a52b888e26cbb92f79" %}
{% set build_number = 3 %}

package:
  name: frozendict-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

outputs:
  - name: {{ name }}
    build:
      script: FROZENDICT_PURE_PY=1 python setup.py install
      noarch: python
      number: {{ build_number * 2 + 1 }}

    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools
        - wheel
      run:
        - python >=3.7

    test:
      requires:
        - python <3.12
      imports:
        - frozendict

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
